### ISSUE TITLE
Server model alias

### ISSUE THREAD

**Issue by amartins23** [lmstudio-ai/lmstudio.js#11]
Some applications expect specific model names when connecting to OpenAI. Since LM Studio presents an OpenAI compatible API, but restricts the model names to a specific structure, it would be useful if when starting the server an alias could be specified for the model name (similar to the --alias parameter in llama.cpp server https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md ).

**Comment by ryan-the-crayon** [comment]
Hi, I believe we already support this via the "identifier".

- If you are loading the model via the CLI (`lms load`), you can pass in a `--identifier` option, such as:

    ```
    lms load lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF --gpu=max --identifier customName
    ```

- If you are loading the model via the API, you can pass in an identifier parameter:

    ```ts
    await client.llm.load("lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF", {
      config: { gpuOffload: "max" },
      identifier: "my-model",
    });
    ```

- If you are loading the model via the multimodel playground page in LM Studio, you can set the identifier in the popup.

**Comment by ryan-the-crayon** [comment]
Closing this for now. Feel free to reopen if these does not address your needs.

**Comment by amartins23** [comment]
I'm sorry, but I don't see any place in the UI to set the identifier either in the "My Models" page or in the "Server" page?

![Server](https://github.com/lmstudio-ai/lmstudio.js/assets/38951957/ed05018e-04b1-4443-a49a-bb921b104276)

![My Models](https://github.com/lmstudio-ai/lmstudio.js/assets/38951957/742a5e5e-ce59-4c1d-9923-cdb52901c2e6)

**Comment by ryan-the-crayon** [comment]
I see. Though, if you are loading models from the chat/server page, you can only load one at the same time. In which case, our OpenAI compatible server will not check for model name. That is, specifying any string as the model would resolve to that one single loaded model. Does this address your needs?

**Comment by amartins23** [comment]
The LM Studio server may not check for the model name, but the software that calls the server will check the model listing and refuse to work if the listed model name does not match what it expects.

**Comment by ryan-the-crayon** [comment]
I see. Is it possible to disable this check in the software you are using? If not, you might need to load models via the multimodel playground or with the CLI. Both methods allow you to specify an identifier (i.e. alias).
