### ISSUE TITLE
message.fragment: Expected object, received string

### ISSUE THREAD

**Issue by danielpervan** [lmstudio-ai/lmstudio.js#146]
I'm trying to set up a simple hello world like program with Node and Typescript, following the examples in the readme.  When I try to query LMStudio, I get the following error (multiple times):

```
This is usually caused by communication protocol incompatibility. Please make sure you are using the up-to-date versions of the SDK and LM Studio.
[LMStudioClient][LLM][ClientPort] Produced communication warning: Received invalid message for channel: endpointName = predict, message = {"type":"fragment","fragment":"I"}. Zod error:

- message.fragment: Expected object, received string
```

LMStudio is running locally on the same machine and the server is running and I can see in the logs that it's receiving requests. I'm using the JS SDK version 0.4.2 and LM Studio 0.3.5 on an M2 Mac. Reading the error message, it obviously suggests version incompatibility between the SDK and the server, but as far as I know, I'm running the latest version of both. Perhaps I'm mistaken? It does however seem like I am getting a response from the server, but the client is unable to parse the data.

Here is my code I'm trying to run:

```
const client = new LMStudioClient();
const loadedModels = await client.llm.listLoaded();
let model;
if (loadedModels.length === 0) {
  process.stdout.write("Loading model...");
  model = await client.llm.load("llama-3.3-70b-instruct", {
    verbose: false,
    onProgress: (progress) => {
      process.stdout.write(`\rLoading model... ${(progress * 100).toFixed(1)}%`);
    },
  });
  console.log("\rLoading model... Done ");
} else {
  console.log("Model already loaded");
  model = await client.llm.get({
    identifier: loadedModels[0].identifier,
  });
}

console.log("Querying model...");
const { content, stats } = await model.respond([
  {
    role: "system",
    content: "You're going to end every message with a knock knock joke.",
  },
  {
    role: "user",
    content: "Hi how are you?",
  },
]);
console.log("Answer: ");
console.log(content);
console.log("Stats: ");
console.log(stats);
console.log("Done");
```

**Comment by YorkieDev** [comment]
@danielpervan what Build version of LM Studio are you running, eg(Build9, Build2)? 

Latest is here: https://lmstudio.ai/beta-releases might be worth giving that a try.

**Comment by danielpervan** [comment]
@YorkieDev Thanks! Yeah, that solved it, of course. I was running build 2 which was what was installed by the built-in updater, even when using the Beta channel. Manually installing build 9 fixed the problem.
