### ISSUE TITLE
How to switch/choose different quantization version from a model path

### ISSUE THREAD

**Issue by emiyalee1005** [lmstudio-ai/lmstudio.js#23]
From document I see something:
`
// Matches any quantization
const llama3 = await client.llm.get({ path: "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF" });
`

Dose it mean to load all quantization version into memory? Or there is method to specify which version to actually load?

**Comment by Trippnology** [comment]
You can load a specific file in the same way, by specifying the full path:

```js
const llama3 = await client.llm.get({ path: "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF/Meta-Llama-3-8B-Instruct-Q8_0.gguf" });
```

**Comment by emiyalee1005** [comment]
> You can load a specific file by adding the full path:
> 
> ```js
> const llama3 = await client.llm.load('lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF/Meta-Llama-3-8B-Instruct-Q8_0.gguf');
> ```

Thanks, it help
