### ISSUE TITLE
- creationParameter.loadConfigStack: Required lm studio - Version 0.2.26 (0.2.26)

### ISSUE THREAD

**Issue by MaatheusGois** [lmstudio-ai/lmstudio.js#42]
W [LMStudioClient][LLM][ClientPort] Received communication warning from the server: Received invalid creationParameter for channel, endpointName = loadModel, creationParameter = {"path":"bartowski/gemma-2-9b-it-GGUF","identifier":"my-model","config":{"contextLength":1024,"gpuOffload":"max"},"noHup":true}. Zod error:

- creationParameter.loadConfigStack: Required

**Comment by yagil** [comment]
Thanks @MaatheusGois should be resolved in 0.2.27 now available on https://lmstudio.ai
