### ISSUE TITLE
How to pass tools?

### ISSUE THREAD

**Issue by MarianoMolina** [lmstudio-ai/lmstudio.js#49]
I'm creating a shallow completions endpoint and I'm wondering about how to pass tools and tool_choice to the respond/complete methods in LLMDynamicHandle. It seems neither can take these opts, yet they are options I've passed to my lm studio server, afaik. What am I missing?

**Comment by Mvb1122** [comment]
What conclusion did you reach? I had this same question and I think that it's just unsupported? I ended up using a custom prompt, but I'd like to know what you thought.

**Comment by MarianoMolina** [comment]
Yep, it is! Its shitty because its supposed to be an OpenAI-like endpoint,
and their endpoint does this parsing.

I can even share my code in case its useful for you:

https://github.com/MarianoMolina/project_alice/blob/main/backend/src/utils/lmStudioManager.ts

**Comment by Mvb1122** [comment]
LMAOOOOO 

Thanks for your help. That's exactly what I was thinking. TBH I'm just gonna swap softwares.

**Comment by MarianoMolina** [comment]
Feel free to check my project. I literally built it from scratch after not
finding what I wanted, and sounds like it should fit your use case. The
project offers a few microservices, one being the backend that offers this
lm studio endpoint.
