### ISSUE TITLE
Searching a model results into error 500

### ISSUE THREAD

**Issue by hopewise** [lmstudio-ai/lmstudio.js#6]
It seems I can't search for models, I keep getting error as in the snapshot:

<img width="1715" alt="Screenshot 2024-04-22 at 6 22 20 PM" src="https://github.com/lmstudio-ai/lmstudio.js/assets/1061157/6c7b56a3-2cc2-443a-a6de-18d505271a8b">
Any idea ?

**Comment by yagil** [comment]
@hopewise this is likely due to Hugging Face networking issues in the last few hours. See: https://x.com/LMStudioAI/status/1782390856986550384

Monitor here: https://status.huggingface.co

**Comment by zacheryph** [comment]
👍 that did work. Hopefully that gets fixed up before confusing too many people.
