### ISSUE TITLE
Deno Compatibility

### ISSUE THREAD

**Issue by swiftsword94** [lmstudio-ai/lmstudio.js#61]
When running lmstudio.js in Deno by importing via "npm:@lmstudio/sdk@^0.1.0"  i get the following error:

```
error: Could not find package 'process' from referrer 'file:///C:/Users/<someuser>/AppData/Local/deno/npm/registry.npmjs.org/@lmstudio/sdk/0.1.0/dist/index.js' (@lmstudio/sdk@0.1.0).
```

Would like to see if there are any options to enable lmstudio to run on deno and if there aren't any, could compatibility be incorporated into lmstudio?

**Comment by swiftsword94** [comment]
it seems when trying these other solutions they aren't working for me:

```
https://unpkg.com/@lmstudio/sdk@0.1.0
https://esm.sh/@lmstudio/sdk@0.1.0
https://cdn.jsdelivr.net/npm/@lmstudio/sdk@0.1.0
```

**Comment by ryan-the-crayon** [comment]
Sorry, it is currently not supported as we use Node.js APIs for many of the tasks. We will definitely look into deno compatibility in the future.

**Comment by swiftsword94** [comment]
In relation to this specific error, both Deno and node support the "node:" specifier for node APIs.

**Comment by ryan-the-crayon** [comment]
Thanks, we will definitely look into this in the future.

**Comment by swiftsword94** [comment]
Just for future reference https://esm.sh/@lmstudio/sdk@0.1.0 running under deno v2.0.0-rc.5 (which should have support for process and other globals defined) is now failing at runtime from the following:

c.WebSocket=window.WebSocket

from package @lmstudio/lms-isomorphic

**Comment by ryan-the-crayon** [comment]
Sorry, I am not really familiar with deno. Though, if you know how to fix this, PR is always welcomed.

**Comment by swiftsword94** [comment]
Well now that deno 2.0 has release with more node compatibility I've seen it start working and have yet to encounter an issue.

**Comment by ryan-the-crayon** [comment]
@swiftsword94 Great news! Thanks for testing it and letting us know. 👍
